/*
 * Copyright 2020 ElectroOptical Innovations, LLC
 * Board.h 
 * Autogenerated file: 2020-09-09T00:42:48.888036
 */

#pragma once


#include "IOPins.h"
#include <Chip.h>
#include <array>
#include <cassert>

#pragma GCC optimize("Os")
#pragma GCC push_options
class Board {
  const Chip::MainClockSpeeds main_clock_frequency_;
  Chip chip_{};
  PinSetter pinsetter_;

  void PinInit(void) const {
    pinsetter_.OpenPinChange();
    IOPins::RxdUSART0.Setup();
    IOPins::TxdUSART0.Setup();
    pinsetter_.ClosePinChange();
  }

 public:

  void Setup(void) {
    chip_.Setup(main_clock_frequency_);
    //  pinsetter_.InitializeGpio();
    PinInit();
    //  chip_.ReadSerialNumber(serial_number_.data(), serial_number_.size());
  }

  template<typename T>
  void SetupPin(T& pin) {
    pinsetter_.OpenPinChange();
    pin.Setup();
    pinsetter_.ClosePinChange();
  }
  explicit Board(Chip::MainClockSpeeds main_clock_frequency)
      : main_clock_frequency_{main_clock_frequency} {}

 private:
  Board(const Board &) = delete;
  Board &operator=(const Board &) = delete;
};

#pragma GCC pop_options
